:github-address: https://github.com/hazelcast-guides/active-directory-authentication
:templates-url: https://raw.githubusercontent.com/hazelcast-guides/adoc-templates/master

= Active Directory authentication

This guide will get you started with the Hazelcast IMDG Enterprise Kerberos authentication
in Microsoft Active Directory domains.

include::{templates-url}/link-to-repo.adoc[]

== What You’ll Learn

In this guide, you will learn how to configure Hazelcast IMDG Enterprise to authenticate
to cluster members and clients using Kerberos tickets in Microsoft Active Directory domain. We will also cover the role mapping based on user's group membership in the
Active Directory.

== Prerequisites

- Hazelcast IMDG Enterprise and its License Key (You can ask for a trial license through the https://hazelcast.com/get-started/#deploymenttype-imdg[license form]).
- Active Directory server (AD) and the 2nd Windows server connected in the Active Directory domain
- JDK 1.8+ (You can get Windows installer on https://www.azul.com/downloads/zulu-community/?version=java-11-lts&os=windows&architecture=x86-64-bit&package=jdk[Azul Zulu download page] for instance.)
- A text editor or IDE

=== Active Directory domain in MS Azure

If you don't have Active Directory domain configured in your environment, you can provision
one in MS Azure. There is an Azure deployment template on GitHub which
starts a domain for you on few clicks:

* https://github.com/maxskunkworks/TLG/tree/master/tlg-base-config_3-vm

== Environment

The sample environment used in this guide contains 2 Windows servers

- Domain controller with Active Directory (hostname: `dc1`)
- Application server attached to the domain (hostname: `app1`)

The servers are connected in a domain named `acme.com`. It's upper-case version
is also the Kerberos realm name (`ACME.COM`).

Hazelcast connections are based on IP addresses, so they will be also necessary in the
Kerberos authentication configuration.

Following addresses are used our environment:

[source]
----
10.0.0.10 dc1
10.0.0.11 app1
----

You have to replace the hostname and IP values to fit your environment in commands
and Hazelcast configuration files used in this guide.

=== Hazelcast port on Windows Firewall

If you have Windows Firewall enabled, then allow access on the default Hazelcast
port numbers (`5701-5703`). You can use the following PowerShell command:

[source,powershell]
----
include::../../../../allow-hazelcast-port.ps1[]
----

=== Kerberos configuration file

Java searches its Kerberos configuration in `krb5.ini` file.
One of its possible locations is the Windows installation directory.
So let's create one simple configuration file `C:\Windows\krb5.ini`
on both servers.

.C:\Windows\krb5.ini
[source,powershell]
----
include::../../../../krb5.ini[]
----

NOTE: Kerberos protocol checks are often case-sensitive. Use the proper form
of principal names and use upper-case Kerberos realm name!

== Create member accounts in Active Directory

We will use the PowerShell on the Domain controller to create an Active Directory
user account for each Hazelcast member.
We don't need to provide passwords, Active Directory will generate random ones for us.
We will also need a keytab file for each member.
Keytab files will contain the password as a shared secret used for authentication and Kerberos
ticket verification.

[source,powershell]
----
New-ADUser -Name hz-app1 -PasswordNotRequired $True `
  -PasswordNeverExpires $True -PassThru -Enabled $True
ktpass -princ hz/10.0.0.11@ACME.COM -mapuser hz-app1@ACME.COM `
  -out hz-app1.keytab +rndPass -ptype KRB5_NT_PRINCIPAL

New-ADUser -Name hz-dc1 -PasswordNotRequired $True `
  -PasswordNeverExpires $True -PassThru -Enabled $True
ktpass -princ hz/10.0.0.10@ACME.COM -mapuser hz-dc1@ACME.COM `
  -out hz-dc1.keytab +rndPass -ptype KRB5_NT_PRINCIPAL
----

The `hz/10.0.0.10@ACME.COM` and `hz/10.0.0.11@ACME.COM` are Service Principal Names (SPN)
and we will reference them in the Hazelcast member configuration.
The `hz/` is a service prefix, followed by the IP address and the Kerberos realm name.

Move the newly generated keytab files to `bin` directory within the Hazelcast
Enterprise installation (e.g. `C:\hazelcast-enterprise-4.1\bin`).

NOTE: As the `hz-app1` account will be used by the application server we need to
move the newly generated `hz-app1.keytab` file from the domain controller
to the application server.

== Configure Hazelcast members

We will use YAML configuration file located in the `bin` directory.
We need to remove the existing member configuration file (`hazelcast.xml`) first.

[source,batch]
----
cd \hazelcast-enterprise-4.1\bin
del hazelcast.xml
----

Now we create the new configuration file called `hazelcast.yml`.
The file will define network discovery method and the security.
Usually there are 3 security realms defined for
The simple form of Kerberos configuration will be used - this should only be used for testing.


.C:\hazelcast-enterprise-4.1\demo\hazelcast.yml
[source,yaml]
----
include::../../../../hazelcast-simple.yml[]
----

Don't forget to replace
`PUT_THE_LICENSE_KEY_HERE` placeholder with a real license key.

A warning message is printed to the console when the simple configuration form is
used for authentication. It gives us hint how to configure the full JAAS authentication.

.Connection initiator warning
[source]
----
WARNING: Using generated Kerberos initiator realm configuration is not intended for production use. It's recommended to properly configure the Krb5LoginModule manually to fit your needs. Following configuration was generated from provided keytab and principal properties:
<realm name="krb5Initiator">
  <authentication>
    <jaas>
      <login-module class-name="com.sun.security.auth.module.Krb5LoginModule" usage="REQUIRED">
        <properties>
          <property name="principal">hz/10.0.0.11@ACME.COM</property>
          <property name="isInitiator">true</property>
          <property name="doNotPrompt">true</property>
          <property name="storeKey">true</property>
          <property name="keyTab">hz-app1.keytab</property>
          <property name="useKeyTab">true</property>
          <property name="refreshKrb5Config">true</property>
        </properties>
      </login-module>
    </jaas>
  </authentication>
</realm>
----

.Connection acceptor warning
[source]
----
WARNING: Using generated Kerberos acceptor realm configuration is not intended for production use. It's recommended to properly configure the Krb5LoginModule manually to fit your needs. Following configuration was generated from provided keytab and principal properties:
<realm name="krb5Acceptor">
  <authentication>
    <jaas>
      <login-module class-name="com.sun.security.auth.module.Krb5LoginModule" usage="REQUIRED">
        <properties>
          <property name="principal">hz/10.0.0.10@ACME.COM</property>
          <property name="isInitiator">false</property>
          <property name="doNotPrompt">true</property>
          <property name="storeKey">true</property>
          <property name="keyTab">hz-dc1.keytab</property>
          <property name="useKeyTab">true</property>
          <property name="refreshKrb5Config">true</property>
        </properties>
      </login-module>
    </jaas>
  </authentication>
</realm>
----

Starting Hazelcast members on both servers should now result in forming
a new Hazelcast cluster with both member.


== Configure Hazelcast Client

Once we have the cluster running we will configure a client.
Its roles will be loaded from the Active Directory using the LDAP protocol.
We will use the existing domain user account for authenticating the client.

=== Create groups and mappings in Active Directory

To demonstrate the recursive role mapping feature, we will define two new
Active Directory groups. The first one, called "Acme Cache" will have its name
referenced in client permissions configuration on Hazelcast members.
The second group "Acme Cache Czechia" will be a member of the first one.
The active domain user (`hazelcast` in our environment)  will be added
as a member to the "Acme Cache Czechia" group.

[source,powershell]
----
include::../../../../create-groups-and-map-user.ps1[]
----

=== Re-configure members

We used the simplified Kerberos configuration when we tried Kerberos
authentication between members. Let's use the full form now. We need it also
to enable Kerberos (GSS-API) authentication into Active Directory's LDAP
interface.

.C:\hazelcast-enterprise-4.1\demo\hazelcast.yml
[source,yaml]
----
include::../../../../hazelcast.yml[]
----

What's new here are the explicitly defined `Krb5LoginModule` configurations
in security realms `krb5Initiator` and `krb5Acceptor`.

We also added the `ldap` sub-section in `kerberos` authentication. It's responsible
for searching recursivelly the group names which are used as client's roles.

The last change is defining the `client-permissions` section. We add one
universal permission which allows clients with role `Acme Cache` assigned all
operations on the cluster.

When we restart the members with this new configuration, they should again form
the cluster. The console is without warnings related to the simplified
Kerberos config now.

=== Check and Prepare Client Environment

We will run Hazelcast Client Demo application on the application Windows Server.

Let's make sure the active user is authenticated to the domain using Kerberos
first.

We can use `klist` tool either from the Java installation or its sibling which
comes in Windows (`C:\Windows\System32\klist.exe`).

[source]
----
C:\Users\hazelcast>klist

Credentials cache: C:\Users\hazelcast\krb5cc_hazelcast

Default principal: hz/10.0.0.11@ACME.COM, 1 entry found.

[1]  Service Principal:  krbtgt/ACME.COM@ACME.COM
     Valid starting:     Nov 05, 2020 19:21:35
     Expires:            Nov 06, 2020 05:21:35
----

=== Configure Hazelcast client

Let's create the `hazelcast-client.yml` configuration file in the `demo` directory
within the Hazelcast installation.

.C:\hazelcast-enterprise-4.1\demo\hazelcast-client.yml
[source,yaml]
----
include::../../../../hazelcast-client.yml[]
----

The Kerberos configuration on the client side is similar to the member configuration.
We just need to define the `kerberos` identity and reference its `Krb5LoginModule`
configuration.

We don't define a keytab file, but we want to use existing credentials,
so we set the `useTicketCache` option value to `true`.

== Troubleshooting

Did anything go wrong in your setup? Try to look in more detail what's
happening underhood. Java provides system properties which allow
you to print Kerberos related debug messages to console. Just edit the Hazelcast
batch files (`start.bat`, `clientConsole.bat`) and add the following arguments to the `java` program call:

[source]
----
-Dsun.security.krb5.debug=true -Dsun.security.jgss.debug=true
----

You can also add the `debug` option to `Krb5LoginModule` configuration. E.g.

[source,yaml]
----
  - name: krb5Initiator
    authentication:
      jaas:
        - class-name: com.sun.security.auth.module.Krb5LoginModule
          usage: REQUIRED
          properties:
            debug: true
----


== Summary

// Provide a quick summary

== See Also
