:github-address: https://github.com/hazelcast-guides/active-directory-authentication
:templates-url: https://raw.githubusercontent.com/hazelcast-guides/adoc-templates/master

= Active Directory authentication

This guide will get you started with the Hazelcast IMDG Enterprise Kerberos authentication
in Microsoft Active Directory domains.

include::{templates-url}/link-to-repo.adoc[]

== What You’ll Learn

In this guide, you will learn how to configure Hazelcast IMDG Enterprise to authenticate
to cluster members and clients using Kerberos tickets in Microsoft Active Directory domain.

== Prerequisites

- Hazelcast IMDG Enterprise and its License Key (You can ask for a trial license through the https://hazelcast.com/get-started/#deploymenttype-imdg[license form]).
- Active Directory server (AD) and the 2nd Windows server connected in the Active Directory domain
- JDK 1.8+ (You can get Windows installer on https://www.azul.com/downloads/zulu-community/?version=java-11-lts&os=windows&architecture=x86-64-bit&package=jdk[Azul Zulu download page] for instance.)
- A text editor or IDE

=== Active Directory domain in MS Azure

If you don't have Active Directory domain configured in your environment, you can provision
one in MS Azure. There is an Azure deployment template on GitHub which
starts a domain for you on few clicks:

* https://github.com/maxskunkworks/TLG/tree/master/tlg-base-config_3-vm

== Environment

The sample environment used in this guide contains 2 Windows servers

- Domain controller with Active Directory (hostname: `dc1`)
- Application server attached to the domain (hostname: `app1`)

The servers are connected in a domain named `acme.com`. It's also the Kerberos
realm name.

Hazelcast connections are based on IP addresses, so they will be also necessary in the
Kerberos authentication configuration.

Following addresses are used our environment:

[source]
----
10.0.0.10 dc1
10.0.0.11 app1
----

You have to replace the hostname and IP values to fit your environment in commands
and Hazelcast configuration files used in this guide.

=== Hazelcast port on Windows Firewall

If you have Windows Firewall enabled, then allow access on the default Hazelcast
port numbers (`5701-5703`). You can use the following PowerShell command:

[source,powershell]
----
include::../../../../allow-hazelcast-port.ps1[]
----

=== Kerberos configuration file

Java searches its Kerberos configuration in `krb5.ini` file.
One of its possible locations is the Windows installation directory.
So let's create one simple configuration file `C:\Windows\krb5.ini`
on both servers.

[source,powershell]
----
include::../../../../krb5.ini[]
----


== Create member accounts in Active Directory

We will use the PowerShell on the Domain controller to create an Active Directory
user account for each Hazelcast member.
We don't need to provide passwords, Active Directory will generate random ones for us.
We will also need a keytab file for each member.
Keytab files will contain the password as a shared secret used for authentication and Kerberos
ticket verification.

[source,powershell]
----
New-ADUser -Name hz-app1 -PasswordNotRequired $True `
  -PasswordNeverExpires $True -PassThru -Enabled $True
ktpass -princ hz/10.0.0.11@acme.com -mapuser hz-app1@acme.com `
  -out hz-app1.keytab +rndPass -ptype KRB5_NT_PRINCIPAL

New-ADUser -Name hz-dc1 -PasswordNotRequired $True `
  -PasswordNeverExpires $True -PassThru -Enabled $True
ktpass -princ hz/10.0.0.10@acme.com -mapuser hz-dc1@acme.com `
  -out hz-dc1.keytab +rndPass -ptype KRB5_NT_PRINCIPAL
----

The `hz/10.0.0.10@acme.com` and `hz/10.0.0.11@acme.com` are Service Principal Names (SPN)
and we will reference them in the Hazelcast member configuration.
The `hz/` is a service prefix, followed by the IP address and the Kerberos realm name.

Move the newly generated keytab files to `bin` directory within the Hazelcast
Enterprise installation (e.g. `C:\hazelcast-enterprise-4.1\bin`).

NOTE: As the `hz-app1` account will be used by the application server we need to
move the newly generated `hz-app1.keytab` file from the domain controller
to the application server.

== Configure Hazelcast members

We will use YAML configuration file located in the `bin`, so we start the member configuration
with removing `hazelcast.xml` file in the same folder.

Now we create the new configuration file called `hazelcast.yml`  in `bin` directory.

.hazelcast.yml
[source,yaml]
----
include::../../../../hazelcast.yml[]
----

It configures network discovery method and security. Don't forget to replace
`PUT_THE_LICENSE_KEY_HERE` placeholder with a real license key.

== Configure Hazelcast Client


== Summary

// Provide a quick summary

== See Also

// Add some links to resources, such as other related guides.
// Use relative links used on the home page (see https://raw.githubusercontent.com/hazelcast-guides/guides-site/master/home/modules/ROOT/pages/index.adoc)

- xref:hazelcast-embedded-springboot:ROOT:index.adoc[Hazelcast in SpringBoot]
- xref:hazelcast-quarkus:ROOT:index.adoc[Hazelcast Client for Quarkus]
